name: Deploy

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "steven743" --password-stdin
    
    - name: Build Docker image
      run: |
        cd HeadsetShopFrontend
        docker build -t headset-shop-frontend:latest .
        docker tag headset-shop-frontend:latest steven743/headset-shop-frontend:latest
        docker push steven743/headset-shop-frontend:latest
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
  
    - name: Install Ansible
      run: pip install ansible

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Run Ansible Playbook
      run: |
        ansible-playbook ansible/deploy.yml -i Ansible/inventory      