services:
  headset-shop-frontend:
    build:
      context: ./HeadsetShopFrontend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT: Development
      - HTTP_PORTS: 5000