- hosts: droplet
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: true
      become: true

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: true
      become: true
    
    - name: Pull API Docker image
      docker_image:
        name: steven743/headset-shop-frontend
        source: pull

    - name: Run API container
      docker_container:
        name: headset-shop-frontend
        image: steven743/headset-shop-frontend
        state: started
        restart_policy: always
        ports:
          - "80:5000"
        env:
          ASPNETCORE_ENVIRONMENT: "Production"
          HTTP_PORTS: 5000