name: Unit Tests

on:
  push:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore headset-shop-frontend.sln

      - name: Run unit tests
        run: dotnet test HeadsetShopFrontend.Test.Unit/HeadsetShopFrontend.Test.Unit.csproj --no-build --verbosity normal